#ifndef BOOTLOADER_CONFIG_H
#define BOOTLOADER_CONFIG_H

#define SRECORD_IMAGE 0

#define IMAGE_FORMAT SRECORD_IMAGE

#define AUTO_BOOTING 0
#define COMMAND_BOOTING 1

#define BOOTING_MODE COMMAND_BOOTING


#endif